/* salah-data.js: the "Your salah" track. GENERATED by tools/salah/build.py; edit
   tools/salah/content.py instead. Status: awaiting teacher review.
   Quran text: Tanzil Project (tanzil.net), CC BY 3.0, verbatim. */
const SALAH = {
 "status": "awaiting teacher review",
 "sources": [
  "Quran text: Tanzil Project (tanzil.net), Tanzil Quran Text (Simple), CC BY 3.0, used verbatim.",
  "Roots of Quran words: Quranic Arabic Corpus (corpus.quran.com), morphology v0.4.",
  "Quran meanings: shown in the app from the Quran Foundation (translation: Saheeh International; word by word: Quran.com), loaded live; the ones here are only the fallback when it can't be reached.",
  "Prayer phrases (not Quran): Rafiq drafts, awaiting teacher review."
 ],
 "parts": [
  {
   "id": "takbir",
   "title": "Opening takbir",
   "ar_title": "تَكْبِيرَةُ الإِحْرامِ",
   "what": "Said with raised hands to begin the prayer; also said at every movement.",
   "group": "prayer",
   "lines": [
    {
     "ar": "اللَّهُ أَكْبَرُ",
     "en": "Allah is the Greatest.",
     "words": [
      {
       "ar": "اللَّهُ",
       "en": "Allah",
       "root": "أله"
      },
      {
       "ar": "أَكْبَرُ",
       "en": "is the Greatest",
       "root": "كبر"
      }
     ]
    }
   ]
  },
  {
   "id": "opening",
   "title": "Opening supplication",
   "ar_title": "دُعاءُ الاسْتِفْتاحِ",
   "what": "Said quietly after the opening takbir, before Al-Fatiha.",
   "group": "prayer",
   "review_note": "Several authentic openings exist (e.g. اللَّهُمَّ باعِدْ بَيْنِي وَبَيْنَ خَطاياي...). This is the short one most commonly taught; the teacher chooses.",
   "lines": [
    {
     "ar": "سُبْحانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبارَكَ اسْمُكَ وَتَعالى جَدُّكَ وَلا إِلٰهَ غَيْرُكَ",
     "en": "Glory be to You, O Allah, and with Your praise. Blessed is Your name, exalted is Your majesty, and there is no god other than You.",
     "words": [
      {
       "ar": "سُبْحانَكَ",
       "en": "Glory be to You",
       "root": "سبح"
      },
      {
       "ar": "اللَّهُمَّ",
       "en": "O Allah",
       "root": "أله"
      },
      {
       "ar": "وَبِحَمْدِكَ",
       "en": "and with Your praise",
       "root": "حمد"
      },
      {
       "ar": "وَتَبارَكَ",
       "en": "and blessed is",
       "root": "برك"
      },
      {
       "ar": "اسْمُكَ",
       "en": "Your name",
       "root": "سمو"
      },
      {
       "ar": "وَتَعالى",
       "en": "and exalted is",
       "root": "علو"
      },
      {
       "ar": "جَدُّكَ",
       "en": "Your majesty",
       "root": "جدد"
      },
      {
       "ar": "وَلا",
       "en": "and there is no",
       "root": ""
      },
      {
       "ar": "إِلٰهَ",
       "en": "god",
       "root": "أله"
      },
      {
       "ar": "غَيْرُكَ",
       "en": "other than You",
       "root": "غير"
      }
     ]
    }
   ]
  },
  {
   "id": "refuge",
   "title": "Seeking refuge",
   "ar_title": "الاسْتِعاذَةُ",
   "what": "Said quietly before reciting Al-Fatiha.",
   "group": "prayer",
   "lines": [
    {
     "ar": "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطانِ الرَّجِيمِ",
     "en": "I seek refuge in Allah from Satan, the outcast.",
     "words": [
      {
       "ar": "أَعُوذُ",
       "en": "I seek refuge",
       "root": "عوذ"
      },
      {
       "ar": "بِاللَّهِ",
       "en": "in Allah",
       "root": "أله"
      },
      {
       "ar": "مِنَ",
       "en": "from",
       "root": ""
      },
      {
       "ar": "الشَّيْطانِ",
       "en": "Satan",
       "root": "شطن"
      },
      {
       "ar": "الرَّجِيمِ",
       "en": "the outcast",
       "root": "رجم"
      }
     ]
    }
   ]
  },
  {
   "id": "fatiha1",
   "title": "Al-Fatiha (1)",
   "ar_title": "الفاتِحَةُ",
   "what": "Recited in every rak'ah: praise of Allah.",
   "group": "prayer",
   "lines": [
    {
     "ref": "1:1",
     "ar": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
     "en": "In the name of Allah, the Most Gracious, the Most Merciful.",
     "words": [
      {
       "ar": "بِسْمِ",
       "en": "In the name",
       "root": "سمو"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      },
      {
       "ar": "الرَّحْمَٰنِ",
       "en": "the Most Gracious",
       "root": "رحم"
      },
      {
       "ar": "الرَّحِيمِ",
       "en": "the Most Merciful",
       "root": "رحم"
      }
     ]
    },
    {
     "ref": "1:2",
     "ar": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
     "en": "All praise is for Allah, Lord of the worlds.",
     "words": [
      {
       "ar": "الْحَمْدُ",
       "en": "All praise",
       "root": "حمد"
      },
      {
       "ar": "لِلَّهِ",
       "en": "is for Allah",
       "root": "أله"
      },
      {
       "ar": "رَبِّ",
       "en": "Lord",
       "root": "ربب"
      },
      {
       "ar": "الْعَالَمِينَ",
       "en": "of the worlds",
       "root": "علم"
      }
     ]
    },
    {
     "ref": "1:3",
     "ar": "الرَّحْمَٰنِ الرَّحِيمِ",
     "en": "The Most Gracious, the Most Merciful.",
     "words": [
      {
       "ar": "الرَّحْمَٰنِ",
       "en": "the Most Gracious",
       "root": "رحم"
      },
      {
       "ar": "الرَّحِيمِ",
       "en": "the Most Merciful",
       "root": "رحم"
      }
     ]
    },
    {
     "ref": "1:4",
     "ar": "مَالِكِ يَوْمِ الدِّينِ",
     "en": "Master of the Day of Judgement.",
     "words": [
      {
       "ar": "مَالِكِ",
       "en": "Master",
       "root": "ملك"
      },
      {
       "ar": "يَوْمِ",
       "en": "of the Day",
       "root": "يوم"
      },
      {
       "ar": "الدِّينِ",
       "en": "of Judgement",
       "root": "دين"
      }
     ]
    }
   ]
  },
  {
   "id": "fatiha2",
   "title": "Al-Fatiha (2)",
   "ar_title": "الفاتِحَةُ",
   "what": "Recited in every rak'ah: the request for guidance.",
   "group": "prayer",
   "lines": [
    {
     "ref": "1:5",
     "ar": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
     "en": "You alone we worship, and You alone we ask for help.",
     "words": [
      {
       "ar": "إِيَّاكَ",
       "en": "You alone",
       "root": ""
      },
      {
       "ar": "نَعْبُدُ",
       "en": "we worship",
       "root": "عبد"
      },
      {
       "ar": "وَإِيَّاكَ",
       "en": "and You alone",
       "root": ""
      },
      {
       "ar": "نَسْتَعِينُ",
       "en": "we ask for help",
       "root": "عون"
      }
     ]
    },
    {
     "ref": "1:6",
     "ar": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
     "en": "Guide us to the straight path,",
     "words": [
      {
       "ar": "اهْدِنَا",
       "en": "Guide us (to)",
       "root": "هدي"
      },
      {
       "ar": "الصِّرَاطَ",
       "en": "the path",
       "root": "صرط"
      },
      {
       "ar": "الْمُسْتَقِيمَ",
       "en": "the straight",
       "root": "قوم"
      }
     ]
    },
    {
     "ref": "1:7",
     "ar": "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
     "en": "the path of those You have blessed, not of those who earned anger, nor of those who went astray.",
     "words": [
      {
       "ar": "صِرَاطَ",
       "en": "the path",
       "root": "صرط"
      },
      {
       "ar": "الَّذِينَ",
       "en": "of those (whom)",
       "root": ""
      },
      {
       "ar": "أَنْعَمْتَ",
       "en": "You have blessed",
       "root": "نعم"
      },
      {
       "ar": "عَلَيْهِمْ",
       "en": "(upon them)",
       "root": ""
      },
      {
       "ar": "غَيْرِ",
       "en": "not (of)",
       "root": "غير"
      },
      {
       "ar": "الْمَغْضُوبِ",
       "en": "those who earned anger",
       "root": "غضب"
      },
      {
       "ar": "عَلَيْهِمْ",
       "en": "(upon them)",
       "root": ""
      },
      {
       "ar": "وَلَا",
       "en": "and nor",
       "root": ""
      },
      {
       "ar": "الضَّالِّينَ",
       "en": "those who went astray",
       "root": "ضلل"
      }
     ]
    },
    {
     "ar": "آمِين",
     "en": "Amin: O Allah, answer our prayer.",
     "words": [
      {
       "ar": "آمِين",
       "en": "Amin (O Allah, answer)",
       "root": ""
      }
     ],
     "review_note": "Not part of the Quran text; said after Al-Fatiha."
    }
   ]
  },
  {
   "id": "ruku",
   "title": "Bowing",
   "ar_title": "الرُّكُوعُ",
   "what": "Said while bowing, usually three times.",
   "group": "prayer",
   "lines": [
    {
     "ar": "سُبْحانَ رَبِّيَ الْعَظِيمِ",
     "en": "Glory be to my Lord, the Magnificent.",
     "words": [
      {
       "ar": "سُبْحانَ",
       "en": "Glory be to",
       "root": "سبح"
      },
      {
       "ar": "رَبِّيَ",
       "en": "my Lord",
       "root": "ربب"
      },
      {
       "ar": "الْعَظِيمِ",
       "en": "the Magnificent",
       "root": "عظم"
      }
     ]
    }
   ]
  },
  {
   "id": "rising",
   "title": "Rising from bowing",
   "ar_title": "الرَّفْعُ مِنَ الرُّكُوعِ",
   "what": "The first line is said while rising; the second once standing.",
   "group": "prayer",
   "review_note": "Also said as رَبَّنا لَكَ الْحَمْدُ (without وَ); both are authentic.",
   "lines": [
    {
     "ar": "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ",
     "en": "Allah hears the one who praises Him.",
     "words": [
      {
       "ar": "سَمِعَ",
       "en": "hears",
       "root": "سمع"
      },
      {
       "ar": "اللَّهُ",
       "en": "Allah",
       "root": "أله"
      },
      {
       "ar": "لِمَنْ",
       "en": "the one who",
       "root": ""
      },
      {
       "ar": "حَمِدَهُ",
       "en": "praises Him",
       "root": "حمد"
      }
     ]
    },
    {
     "ar": "رَبَّنا وَلَكَ الْحَمْدُ",
     "en": "Our Lord, and to You belongs all praise.",
     "words": [
      {
       "ar": "رَبَّنا",
       "en": "Our Lord",
       "root": "ربب"
      },
      {
       "ar": "وَلَكَ",
       "en": "and to You (belongs)",
       "root": ""
      },
      {
       "ar": "الْحَمْدُ",
       "en": "all praise",
       "root": "حمد"
      }
     ]
    }
   ]
  },
  {
   "id": "sujud",
   "title": "Prostration",
   "ar_title": "السُّجُودُ",
   "what": "Said in prostration, usually three times; the second line between the two prostrations.",
   "group": "prayer",
   "lines": [
    {
     "ar": "سُبْحانَ رَبِّيَ الْأَعْلى",
     "en": "Glory be to my Lord, the Most High.",
     "words": [
      {
       "ar": "سُبْحانَ",
       "en": "Glory be to",
       "root": "سبح"
      },
      {
       "ar": "رَبِّيَ",
       "en": "my Lord",
       "root": "ربب"
      },
      {
       "ar": "الْأَعْلى",
       "en": "the Most High",
       "root": "علو"
      }
     ]
    },
    {
     "ar": "رَبِّ اغْفِرْ لِي",
     "en": "My Lord, forgive me.",
     "words": [
      {
       "ar": "رَبِّ",
       "en": "My Lord",
       "root": "ربب"
      },
      {
       "ar": "اغْفِرْ",
       "en": "forgive",
       "root": "غفر"
      },
      {
       "ar": "لِي",
       "en": "me",
       "root": ""
      }
     ]
    }
   ]
  },
  {
   "id": "tashahhud",
   "title": "Tashahhud",
   "ar_title": "التَّشَهُّدُ",
   "what": "Said while sitting, after every second rak'ah and at the end of the prayer.",
   "group": "prayer",
   "review_note": "This is the wording narrated by Ibn Mas'ud. Other authentic wordings exist (e.g. Ibn Abbas: التَّحِيّاتُ الْمُبارَكاتُ...); the teacher chooses.",
   "lines": [
    {
     "ar": "التَّحِيّاتُ لِلَّهِ وَالصَّلَواتُ وَالطَّيِّباتُ",
     "en": "All greetings are for Allah, and the prayers and the good things.",
     "words": [
      {
       "ar": "التَّحِيّاتُ",
       "en": "All greetings",
       "root": "حيي"
      },
      {
       "ar": "لِلَّهِ",
       "en": "are for Allah",
       "root": "أله"
      },
      {
       "ar": "وَالصَّلَواتُ",
       "en": "and the prayers",
       "root": "صلو"
      },
      {
       "ar": "وَالطَّيِّباتُ",
       "en": "and the good things",
       "root": "طيب"
      }
     ]
    },
    {
     "ar": "السَّلامُ عَلَيْكَ أَيُّها النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكاتُهُ",
     "en": "Peace be upon you, O Prophet, and the mercy of Allah and His blessings.",
     "words": [
      {
       "ar": "السَّلامُ",
       "en": "Peace",
       "root": "سلم"
      },
      {
       "ar": "عَلَيْكَ",
       "en": "be upon you",
       "root": ""
      },
      {
       "ar": "أَيُّها",
       "en": "O",
       "root": ""
      },
      {
       "ar": "النَّبِيُّ",
       "en": "Prophet",
       "root": "نبأ"
      },
      {
       "ar": "وَرَحْمَةُ",
       "en": "and the mercy",
       "root": "رحم"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      },
      {
       "ar": "وَبَرَكاتُهُ",
       "en": "and His blessings",
       "root": "برك"
      }
     ]
    },
    {
     "ar": "السَّلامُ عَلَيْنا وَعَلى عِبادِ اللَّهِ الصّالِحِينَ",
     "en": "Peace be upon us and upon the righteous servants of Allah.",
     "words": [
      {
       "ar": "السَّلامُ",
       "en": "Peace",
       "root": "سلم"
      },
      {
       "ar": "عَلَيْنا",
       "en": "be upon us",
       "root": ""
      },
      {
       "ar": "وَعَلى",
       "en": "and upon",
       "root": ""
      },
      {
       "ar": "عِبادِ",
       "en": "the servants",
       "root": "عبد"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      },
      {
       "ar": "الصّالِحِينَ",
       "en": "the righteous",
       "root": "صلح"
      }
     ]
    },
    {
     "ar": "أَشْهَدُ أَنْ لا إِلٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
     "en": "I bear witness that there is no god except Allah, and I bear witness that Muhammad is His servant and His Messenger.",
     "words": [
      {
       "ar": "أَشْهَدُ",
       "en": "I bear witness",
       "root": "شهد"
      },
      {
       "ar": "أَنْ",
       "en": "that",
       "root": ""
      },
      {
       "ar": "لا",
       "en": "there is no",
       "root": ""
      },
      {
       "ar": "إِلٰهَ",
       "en": "god",
       "root": "أله"
      },
      {
       "ar": "إِلَّا",
       "en": "except",
       "root": ""
      },
      {
       "ar": "اللَّهُ",
       "en": "Allah",
       "root": "أله"
      },
      {
       "ar": "وَأَشْهَدُ",
       "en": "and I bear witness",
       "root": "شهد"
      },
      {
       "ar": "أَنَّ",
       "en": "that",
       "root": ""
      },
      {
       "ar": "مُحَمَّدًا",
       "en": "Muhammad",
       "root": "حمد"
      },
      {
       "ar": "عَبْدُهُ",
       "en": "is His servant",
       "root": "عبد"
      },
      {
       "ar": "وَرَسُولُهُ",
       "en": "and His Messenger",
       "root": "رسل"
      }
     ]
    }
   ]
  },
  {
   "id": "salawat",
   "title": "Blessings on the Prophet",
   "ar_title": "الصَّلاةُ الإِبْراهِيمِيَّةُ",
   "what": "Said in the final sitting, after the tashahhud.",
   "group": "prayer",
   "review_note": "Wording varies slightly between narrations; the teacher chooses.",
   "lines": [
    {
     "ar": "اللَّهُمَّ صَلِّ عَلى مُحَمَّدٍ وَعَلى آلِ مُحَمَّدٍ",
     "en": "O Allah, send prayers upon Muhammad and upon the family of Muhammad,",
     "words": [
      {
       "ar": "اللَّهُمَّ",
       "en": "O Allah",
       "root": "أله"
      },
      {
       "ar": "صَلِّ",
       "en": "send prayers",
       "root": "صلو"
      },
      {
       "ar": "عَلى",
       "en": "upon",
       "root": ""
      },
      {
       "ar": "مُحَمَّدٍ",
       "en": "Muhammad",
       "root": "حمد"
      },
      {
       "ar": "وَعَلى",
       "en": "and upon",
       "root": ""
      },
      {
       "ar": "آلِ",
       "en": "the family",
       "root": "أول"
      },
      {
       "ar": "مُحَمَّدٍ",
       "en": "of Muhammad",
       "root": "حمد"
      }
     ]
    },
    {
     "ar": "كَما صَلَّيْتَ عَلى إِبْراهِيمَ وَعَلى آلِ إِبْراهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
     "en": "as You sent prayers upon Ibrahim and upon the family of Ibrahim. Indeed, You are Praiseworthy, Glorious.",
     "words": [
      {
       "ar": "كَما",
       "en": "as",
       "root": ""
      },
      {
       "ar": "صَلَّيْتَ",
       "en": "You sent prayers",
       "root": "صلو"
      },
      {
       "ar": "عَلى",
       "en": "upon",
       "root": ""
      },
      {
       "ar": "إِبْراهِيمَ",
       "en": "Ibrahim",
       "root": ""
      },
      {
       "ar": "وَعَلى",
       "en": "and upon",
       "root": ""
      },
      {
       "ar": "آلِ",
       "en": "the family",
       "root": "أول"
      },
      {
       "ar": "إِبْراهِيمَ",
       "en": "of Ibrahim",
       "root": ""
      },
      {
       "ar": "إِنَّكَ",
       "en": "Indeed You are",
       "root": ""
      },
      {
       "ar": "حَمِيدٌ",
       "en": "Praiseworthy",
       "root": "حمد"
      },
      {
       "ar": "مَجِيدٌ",
       "en": "Glorious",
       "root": "مجد"
      }
     ]
    },
    {
     "ar": "اللَّهُمَّ بارِكْ عَلى مُحَمَّدٍ وَعَلى آلِ مُحَمَّدٍ",
     "en": "O Allah, bless Muhammad and the family of Muhammad,",
     "words": [
      {
       "ar": "اللَّهُمَّ",
       "en": "O Allah",
       "root": "أله"
      },
      {
       "ar": "بارِكْ",
       "en": "bless",
       "root": "برك"
      },
      {
       "ar": "عَلى",
       "en": "(upon)",
       "root": ""
      },
      {
       "ar": "مُحَمَّدٍ",
       "en": "Muhammad",
       "root": "حمد"
      },
      {
       "ar": "وَعَلى",
       "en": "and (upon)",
       "root": ""
      },
      {
       "ar": "آلِ",
       "en": "the family",
       "root": "أول"
      },
      {
       "ar": "مُحَمَّدٍ",
       "en": "of Muhammad",
       "root": "حمد"
      }
     ]
    },
    {
     "ar": "كَما بارَكْتَ عَلى إِبْراهِيمَ وَعَلى آلِ إِبْراهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ",
     "en": "as You blessed Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy, Glorious.",
     "words": [
      {
       "ar": "كَما",
       "en": "as",
       "root": ""
      },
      {
       "ar": "بارَكْتَ",
       "en": "You blessed",
       "root": "برك"
      },
      {
       "ar": "عَلى",
       "en": "(upon)",
       "root": ""
      },
      {
       "ar": "إِبْراهِيمَ",
       "en": "Ibrahim",
       "root": ""
      },
      {
       "ar": "وَعَلى",
       "en": "and (upon)",
       "root": ""
      },
      {
       "ar": "آلِ",
       "en": "the family",
       "root": "أول"
      },
      {
       "ar": "إِبْراهِيمَ",
       "en": "of Ibrahim",
       "root": ""
      },
      {
       "ar": "إِنَّكَ",
       "en": "Indeed You are",
       "root": ""
      },
      {
       "ar": "حَمِيدٌ",
       "en": "Praiseworthy",
       "root": "حمد"
      },
      {
       "ar": "مَجِيدٌ",
       "en": "Glorious",
       "root": "مجد"
      }
     ]
    }
   ]
  },
  {
   "id": "taslim",
   "title": "Closing salam",
   "ar_title": "التَّسْلِيمُ",
   "what": "Said turning the head to the right, then to the left, to end the prayer.",
   "group": "prayer",
   "lines": [
    {
     "ar": "السَّلامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
     "en": "Peace be upon you and the mercy of Allah.",
     "words": [
      {
       "ar": "السَّلامُ",
       "en": "Peace",
       "root": "سلم"
      },
      {
       "ar": "عَلَيْكُمْ",
       "en": "be upon you",
       "root": ""
      },
      {
       "ar": "وَرَحْمَةُ",
       "en": "and the mercy",
       "root": "رحم"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      }
     ]
    }
   ]
  },
  {
   "id": "ikhlas",
   "title": "Al-Ikhlas",
   "ar_title": "الإِخْلاصُ",
   "what": "Sincerity: who Allah is.",
   "group": "surah",
   "surah": 112,
   "lines": [
    {
     "ref": "112:1",
     "ar": "قُلْ هُوَ اللَّهُ أَحَدٌ",
     "en": "Say: He is Allah, the One.",
     "words": [
      {
       "ar": "قُلْ",
       "en": "Say",
       "root": "قول"
      },
      {
       "ar": "هُوَ",
       "en": "He",
       "root": ""
      },
      {
       "ar": "اللَّهُ",
       "en": "is Allah",
       "root": "أله"
      },
      {
       "ar": "أَحَدٌ",
       "en": "the One",
       "root": "أحد"
      }
     ]
    },
    {
     "ref": "112:2",
     "ar": "اللَّهُ الصَّمَدُ",
     "en": "Allah, the Eternal Refuge.",
     "words": [
      {
       "ar": "اللَّهُ",
       "en": "Allah",
       "root": "أله"
      },
      {
       "ar": "الصَّمَدُ",
       "en": "the Eternal Refuge",
       "root": "صمد"
      }
     ]
    },
    {
     "ref": "112:3",
     "ar": "لَمْ يَلِدْ وَلَمْ يُولَدْ",
     "en": "He does not give birth, nor was He born,",
     "words": [
      {
       "ar": "لَمْ",
       "en": "He does not",
       "root": ""
      },
      {
       "ar": "يَلِدْ",
       "en": "give birth",
       "root": "ولد"
      },
      {
       "ar": "وَلَمْ",
       "en": "and not",
       "root": ""
      },
      {
       "ar": "يُولَدْ",
       "en": "was He born",
       "root": "ولد"
      }
     ]
    },
    {
     "ref": "112:4",
     "ar": "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
     "en": "and there is none equal to Him.",
     "words": [
      {
       "ar": "وَلَمْ",
       "en": "and not",
       "root": ""
      },
      {
       "ar": "يَكُن",
       "en": "is",
       "root": "كون"
      },
      {
       "ar": "لَّهُ",
       "en": "to Him",
       "root": ""
      },
      {
       "ar": "كُفُوًا",
       "en": "equal",
       "root": "كفأ"
      },
      {
       "ar": "أَحَدٌ",
       "en": "anyone",
       "root": "أحد"
      }
     ]
    }
   ]
  },
  {
   "id": "falaq",
   "title": "Al-Falaq",
   "ar_title": "الفَلَقُ",
   "what": "Daybreak: seeking protection from harm.",
   "group": "surah",
   "surah": 113,
   "lines": [
    {
     "ref": "113:1",
     "ar": "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ",
     "en": "Say: I seek refuge in the Lord of the daybreak",
     "words": [
      {
       "ar": "قُلْ",
       "en": "Say",
       "root": "قول"
      },
      {
       "ar": "أَعُوذُ",
       "en": "I seek refuge",
       "root": "عوذ"
      },
      {
       "ar": "بِرَبِّ",
       "en": "in the Lord",
       "root": "ربب"
      },
      {
       "ar": "الْفَلَقِ",
       "en": "of the daybreak",
       "root": "فلق"
      }
     ]
    },
    {
     "ref": "113:2",
     "ar": "مِن شَرِّ مَا خَلَقَ",
     "en": "from the evil of what He created,",
     "words": [
      {
       "ar": "مِن",
       "en": "from",
       "root": ""
      },
      {
       "ar": "شَرِّ",
       "en": "the evil",
       "root": "شرر"
      },
      {
       "ar": "مَا",
       "en": "of what",
       "root": ""
      },
      {
       "ar": "خَلَقَ",
       "en": "He created",
       "root": "خلق"
      }
     ]
    },
    {
     "ref": "113:3",
     "ar": "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
     "en": "and from the evil of the darkness when it settles,",
     "words": [
      {
       "ar": "وَمِن",
       "en": "and from",
       "root": ""
      },
      {
       "ar": "شَرِّ",
       "en": "the evil",
       "root": "شرر"
      },
      {
       "ar": "غَاسِقٍ",
       "en": "of darkness",
       "root": "غسق"
      },
      {
       "ar": "إِذَا",
       "en": "when",
       "root": ""
      },
      {
       "ar": "وَقَبَ",
       "en": "it settles",
       "root": "وقب"
      }
     ]
    },
    {
     "ref": "113:4",
     "ar": "وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ",
     "en": "and from the evil of those who blow on knots,",
     "words": [
      {
       "ar": "وَمِن",
       "en": "and from",
       "root": ""
      },
      {
       "ar": "شَرِّ",
       "en": "the evil",
       "root": "شرر"
      },
      {
       "ar": "النَّفَّاثَاتِ",
       "en": "of those who blow",
       "root": "نفث"
      },
      {
       "ar": "فِي",
       "en": "on",
       "root": ""
      },
      {
       "ar": "الْعُقَدِ",
       "en": "knots",
       "root": "عقد"
      }
     ]
    },
    {
     "ref": "113:5",
     "ar": "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
     "en": "and from the evil of an envier when he envies.",
     "words": [
      {
       "ar": "وَمِن",
       "en": "and from",
       "root": ""
      },
      {
       "ar": "شَرِّ",
       "en": "the evil",
       "root": "شرر"
      },
      {
       "ar": "حَاسِدٍ",
       "en": "of an envier",
       "root": "حسد"
      },
      {
       "ar": "إِذَا",
       "en": "when",
       "root": ""
      },
      {
       "ar": "حَسَدَ",
       "en": "he envies",
       "root": "حسد"
      }
     ]
    }
   ]
  },
  {
   "id": "nas",
   "title": "An-Nas",
   "ar_title": "النّاسُ",
   "what": "Mankind: seeking protection from the whisperer.",
   "group": "surah",
   "surah": 114,
   "lines": [
    {
     "ref": "114:1",
     "ar": "قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
     "en": "Say: I seek refuge in the Lord of mankind,",
     "words": [
      {
       "ar": "قُلْ",
       "en": "Say",
       "root": "قول"
      },
      {
       "ar": "أَعُوذُ",
       "en": "I seek refuge",
       "root": "عوذ"
      },
      {
       "ar": "بِرَبِّ",
       "en": "in the Lord",
       "root": "ربب"
      },
      {
       "ar": "النَّاسِ",
       "en": "of mankind",
       "root": "أنس"
      }
     ]
    },
    {
     "ref": "114:2",
     "ar": "مَلِكِ النَّاسِ",
     "en": "the King of mankind,",
     "words": [
      {
       "ar": "مَلِكِ",
       "en": "the King",
       "root": "ملك"
      },
      {
       "ar": "النَّاسِ",
       "en": "of mankind",
       "root": "أنس"
      }
     ]
    },
    {
     "ref": "114:3",
     "ar": "إِلَٰهِ النَّاسِ",
     "en": "the God of mankind,",
     "words": [
      {
       "ar": "إِلَٰهِ",
       "en": "the God",
       "root": "أله"
      },
      {
       "ar": "النَّاسِ",
       "en": "of mankind",
       "root": "أنس"
      }
     ]
    },
    {
     "ref": "114:4",
     "ar": "مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
     "en": "from the evil of the whisperer who withdraws,",
     "words": [
      {
       "ar": "مِن",
       "en": "from",
       "root": ""
      },
      {
       "ar": "شَرِّ",
       "en": "the evil",
       "root": "شرر"
      },
      {
       "ar": "الْوَسْوَاسِ",
       "en": "of the whisperer",
       "root": "وسوس"
      },
      {
       "ar": "الْخَنَّاسِ",
       "en": "who withdraws",
       "root": "خنس"
      }
     ]
    },
    {
     "ref": "114:5",
     "ar": "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ",
     "en": "who whispers into the hearts of mankind,",
     "words": [
      {
       "ar": "الَّذِي",
       "en": "who",
       "root": ""
      },
      {
       "ar": "يُوَسْوِسُ",
       "en": "whispers",
       "root": "وسوس"
      },
      {
       "ar": "فِي",
       "en": "into",
       "root": ""
      },
      {
       "ar": "صُدُورِ",
       "en": "the chests (hearts)",
       "root": "صدر"
      },
      {
       "ar": "النَّاسِ",
       "en": "of mankind",
       "root": "أنس"
      }
     ]
    },
    {
     "ref": "114:6",
     "ar": "مِنَ الْجِنَّةِ وَالنَّاسِ",
     "en": "from among the jinn and mankind.",
     "words": [
      {
       "ar": "مِنَ",
       "en": "from among",
       "root": ""
      },
      {
       "ar": "الْجِنَّةِ",
       "en": "the jinn",
       "root": "جنن"
      },
      {
       "ar": "وَالنَّاسِ",
       "en": "and mankind",
       "root": "أنس"
      }
     ]
    }
   ]
  },
  {
   "id": "kawthar",
   "title": "Al-Kawthar",
   "ar_title": "الكَوْثَرُ",
   "what": "Abundance: the gift given to the Prophet ﷺ.",
   "group": "surah",
   "surah": 108,
   "lines": [
    {
     "ref": "108:1",
     "ar": "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ",
     "en": "Indeed, We have given you al-Kawthar (abundant good).",
     "words": [
      {
       "ar": "إِنَّا",
       "en": "Indeed We",
       "root": ""
      },
      {
       "ar": "أَعْطَيْنَاكَ",
       "en": "have given you",
       "root": "عطو"
      },
      {
       "ar": "الْكَوْثَرَ",
       "en": "al-Kawthar (abundance)",
       "root": "كثر"
      }
     ]
    },
    {
     "ref": "108:2",
     "ar": "فَصَلِّ لِرَبِّكَ وَانْحَرْ",
     "en": "So pray to your Lord and sacrifice.",
     "words": [
      {
       "ar": "فَصَلِّ",
       "en": "So pray",
       "root": "صلو"
      },
      {
       "ar": "لِرَبِّكَ",
       "en": "to your Lord",
       "root": "ربب"
      },
      {
       "ar": "وَانْحَرْ",
       "en": "and sacrifice",
       "root": "نحر"
      }
     ]
    },
    {
     "ref": "108:3",
     "ar": "إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ",
     "en": "Indeed, your enemy is the one cut off.",
     "words": [
      {
       "ar": "إِنَّ",
       "en": "Indeed",
       "root": ""
      },
      {
       "ar": "شَانِئَكَ",
       "en": "your enemy",
       "root": "شنأ"
      },
      {
       "ar": "هُوَ",
       "en": "he",
       "root": ""
      },
      {
       "ar": "الْأَبْتَرُ",
       "en": "is the one cut off",
       "root": "بتر"
      }
     ]
    }
   ]
  },
  {
   "id": "nasr",
   "title": "An-Nasr",
   "ar_title": "النَّصْرُ",
   "what": "Help: victory, praise and seeking forgiveness.",
   "group": "surah",
   "surah": 110,
   "lines": [
    {
     "ref": "110:1",
     "ar": "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ",
     "en": "When the help of Allah comes, and the victory,",
     "words": [
      {
       "ar": "إِذَا",
       "en": "When",
       "root": ""
      },
      {
       "ar": "جَاءَ",
       "en": "comes",
       "root": "جيأ"
      },
      {
       "ar": "نَصْرُ",
       "en": "the help",
       "root": "نصر"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      },
      {
       "ar": "وَالْفَتْحُ",
       "en": "and the victory",
       "root": "فتح"
      }
     ]
    },
    {
     "ref": "110:2",
     "ar": "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا",
     "en": "and you see people entering the religion of Allah in crowds,",
     "words": [
      {
       "ar": "وَرَأَيْتَ",
       "en": "and you see",
       "root": "رأي"
      },
      {
       "ar": "النَّاسَ",
       "en": "the people",
       "root": "أنس"
      },
      {
       "ar": "يَدْخُلُونَ",
       "en": "entering",
       "root": "دخل"
      },
      {
       "ar": "فِي",
       "en": "into",
       "root": ""
      },
      {
       "ar": "دِينِ",
       "en": "the religion",
       "root": "دين"
      },
      {
       "ar": "اللَّهِ",
       "en": "of Allah",
       "root": "أله"
      },
      {
       "ar": "أَفْوَاجًا",
       "en": "in crowds",
       "root": "فوج"
      }
     ]
    },
    {
     "ref": "110:3",
     "ar": "فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا",
     "en": "then glorify your Lord with praise and ask His forgiveness. Indeed, He always accepts repentance.",
     "words": [
      {
       "ar": "فَسَبِّحْ",
       "en": "then glorify",
       "root": "سبح"
      },
      {
       "ar": "بِحَمْدِ",
       "en": "with the praise",
       "root": "حمد"
      },
      {
       "ar": "رَبِّكَ",
       "en": "of your Lord",
       "root": "ربب"
      },
      {
       "ar": "وَاسْتَغْفِرْهُ",
       "en": "and ask His forgiveness",
       "root": "غفر"
      },
      {
       "ar": "إِنَّهُ",
       "en": "Indeed He",
       "root": ""
      },
      {
       "ar": "كَانَ",
       "en": "is ever",
       "root": "كون"
      },
      {
       "ar": "تَوَّابًا",
       "en": "accepting of repentance",
       "root": "توب"
      }
     ]
    }
   ]
  },
  {
   "id": "kafirun",
   "title": "Al-Kafirun",
   "ar_title": "الكافِرُونَ",
   "what": "The disbelievers: to you your religion, to me mine.",
   "group": "surah",
   "surah": 109,
   "lines": [
    {
     "ref": "109:1",
     "ar": "قُلْ يَا أَيُّهَا الْكَافِرُونَ",
     "en": "Say: O disbelievers,",
     "words": [
      {
       "ar": "قُلْ",
       "en": "Say",
       "root": "قول"
      },
      {
       "ar": "يَا",
       "en": "O",
       "root": ""
      },
      {
       "ar": "أَيُّهَا",
       "en": "(you)",
       "root": ""
      },
      {
       "ar": "الْكَافِرُونَ",
       "en": "disbelievers",
       "root": "كفر"
      }
     ]
    },
    {
     "ref": "109:2",
     "ar": "لَا أَعْبُدُ مَا تَعْبُدُونَ",
     "en": "I do not worship what you worship,",
     "words": [
      {
       "ar": "لَا",
       "en": "I do not",
       "root": ""
      },
      {
       "ar": "أَعْبُدُ",
       "en": "worship",
       "root": "عبد"
      },
      {
       "ar": "مَا",
       "en": "what",
       "root": ""
      },
      {
       "ar": "تَعْبُدُونَ",
       "en": "you worship",
       "root": "عبد"
      }
     ]
    },
    {
     "ref": "109:3",
     "ar": "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ",
     "en": "nor do you worship what I worship,",
     "words": [
      {
       "ar": "وَلَا",
       "en": "nor",
       "root": ""
      },
      {
       "ar": "أَنتُمْ",
       "en": "are you",
       "root": ""
      },
      {
       "ar": "عَابِدُونَ",
       "en": "worshippers",
       "root": "عبد"
      },
      {
       "ar": "مَا",
       "en": "of what",
       "root": ""
      },
      {
       "ar": "أَعْبُدُ",
       "en": "I worship",
       "root": "عبد"
      }
     ]
    },
    {
     "ref": "109:4",
     "ar": "وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ",
     "en": "nor will I worship what you worship,",
     "words": [
      {
       "ar": "وَلَا",
       "en": "nor",
       "root": ""
      },
      {
       "ar": "أَنَا",
       "en": "am I",
       "root": ""
      },
      {
       "ar": "عَابِدٌ",
       "en": "a worshipper",
       "root": "عبد"
      },
      {
       "ar": "مَّا",
       "en": "of what",
       "root": ""
      },
      {
       "ar": "عَبَدتُّمْ",
       "en": "you worship",
       "root": "عبد"
      }
     ]
    },
    {
     "ref": "109:5",
     "ar": "وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ",
     "en": "nor will you worship what I worship.",
     "words": [
      {
       "ar": "وَلَا",
       "en": "nor",
       "root": ""
      },
      {
       "ar": "أَنتُمْ",
       "en": "are you",
       "root": ""
      },
      {
       "ar": "عَابِدُونَ",
       "en": "worshippers",
       "root": "عبد"
      },
      {
       "ar": "مَا",
       "en": "of what",
       "root": ""
      },
      {
       "ar": "أَعْبُدُ",
       "en": "I worship",
       "root": "عبد"
      }
     ]
    },
    {
     "ref": "109:6",
     "ar": "لَكُمْ دِينُكُمْ وَلِيَ دِينِ",
     "en": "To you your religion, and to me mine.",
     "words": [
      {
       "ar": "لَكُمْ",
       "en": "To you",
       "root": ""
      },
      {
       "ar": "دِينُكُمْ",
       "en": "your religion",
       "root": "دين"
      },
      {
       "ar": "وَلِيَ",
       "en": "and to me",
       "root": ""
      },
      {
       "ar": "دِينِ",
       "en": "my religion",
       "root": "دين"
      }
     ]
    }
   ]
  },
  {
   "id": "masad",
   "title": "Al-Masad",
   "ar_title": "المَسَدُ",
   "what": "Palm fibre: the fate of Abu Lahab.",
   "group": "surah",
   "surah": 111,
   "lines": [
    {
     "ref": "111:1",
     "ar": "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ",
     "en": "May the hands of Abu Lahab perish, and may he perish.",
     "words": [
      {
       "ar": "تَبَّتْ",
       "en": "Perish",
       "root": "تبب"
      },
      {
       "ar": "يَدَا",
       "en": "the two hands",
       "root": "يدي"
      },
      {
       "ar": "أَبِي",
       "en": "of Abu",
       "root": "أبو"
      },
      {
       "ar": "لَهَبٍ",
       "en": "Lahab",
       "root": "لهب"
      },
      {
       "ar": "وَتَبَّ",
       "en": "and he perished",
       "root": "تبب"
      }
     ]
    },
    {
     "ref": "111:2",
     "ar": "مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ",
     "en": "His wealth and what he earned will not help him.",
     "words": [
      {
       "ar": "مَا",
       "en": "Will not",
       "root": ""
      },
      {
       "ar": "أَغْنَىٰ",
       "en": "help",
       "root": "غني"
      },
      {
       "ar": "عَنْهُ",
       "en": "him",
       "root": ""
      },
      {
       "ar": "مَالُهُ",
       "en": "his wealth",
       "root": "مول"
      },
      {
       "ar": "وَمَا",
       "en": "and what",
       "root": ""
      },
      {
       "ar": "كَسَبَ",
       "en": "he earned",
       "root": "كسب"
      }
     ]
    },
    {
     "ref": "111:3",
     "ar": "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ",
     "en": "He will burn in a fire of blazing flame,",
     "words": [
      {
       "ar": "سَيَصْلَىٰ",
       "en": "He will burn",
       "root": "صلي"
      },
      {
       "ar": "نَارًا",
       "en": "(in) a fire",
       "root": "نور"
      },
      {
       "ar": "ذَاتَ",
       "en": "of",
       "root": ""
      },
      {
       "ar": "لَهَبٍ",
       "en": "blazing flame",
       "root": "لهب"
      }
     ]
    },
    {
     "ref": "111:4",
     "ar": "وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ",
     "en": "and his wife, the carrier of firewood,",
     "words": [
      {
       "ar": "وَامْرَأَتُهُ",
       "en": "and his wife",
       "root": "مرأ"
      },
      {
       "ar": "حَمَّالَةَ",
       "en": "the carrier",
       "root": "حمل"
      },
      {
       "ar": "الْحَطَبِ",
       "en": "of firewood",
       "root": "حطب"
      }
     ]
    },
    {
     "ref": "111:5",
     "ar": "فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ",
     "en": "around her neck a rope of palm fibre.",
     "words": [
      {
       "ar": "فِي",
       "en": "around",
       "root": ""
      },
      {
       "ar": "جِيدِهَا",
       "en": "her neck",
       "root": "جيد"
      },
      {
       "ar": "حَبْلٌ",
       "en": "a rope",
       "root": "حبل"
      },
      {
       "ar": "مِّن",
       "en": "of",
       "root": ""
      },
      {
       "ar": "مَّسَدٍ",
       "en": "palm fibre",
       "root": "مسد"
      }
     ]
    }
   ]
  },
  {
   "id": "maun",
   "title": "Al-Ma'un",
   "ar_title": "الماعُونَ",
   "what": "Small kindnesses: true prayer and helping others.",
   "group": "surah",
   "surah": 107,
   "lines": [
    {
     "ref": "107:1",
     "ar": "أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ",
     "en": "Have you seen the one who denies the Judgement?",
     "words": [
      {
       "ar": "أَرَأَيْتَ",
       "en": "Have you seen",
       "root": "رأي"
      },
      {
       "ar": "الَّذِي",
       "en": "the one who",
       "root": ""
      },
      {
       "ar": "يُكَذِّبُ",
       "en": "denies",
       "root": "كذب"
      },
      {
       "ar": "بِالدِّينِ",
       "en": "the Judgement",
       "root": "دين"
      }
     ]
    },
    {
     "ref": "107:2",
     "ar": "فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ",
     "en": "That is the one who pushes away the orphan",
     "words": [
      {
       "ar": "فَذَٰلِكَ",
       "en": "That",
       "root": ""
      },
      {
       "ar": "الَّذِي",
       "en": "is the one who",
       "root": ""
      },
      {
       "ar": "يَدُعُّ",
       "en": "pushes away",
       "root": "دعع"
      },
      {
       "ar": "الْيَتِيمَ",
       "en": "the orphan",
       "root": "يتم"
      }
     ]
    },
    {
     "ref": "107:3",
     "ar": "وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ",
     "en": "and does not encourage feeding the poor.",
     "words": [
      {
       "ar": "وَلَا",
       "en": "and does not",
       "root": ""
      },
      {
       "ar": "يَحُضُّ",
       "en": "encourage",
       "root": "حضض"
      },
      {
       "ar": "عَلَىٰ",
       "en": "(to)",
       "root": ""
      },
      {
       "ar": "طَعَامِ",
       "en": "feeding",
       "root": "طعم"
      },
      {
       "ar": "الْمِسْكِينِ",
       "en": "the poor",
       "root": "سكن"
      }
     ]
    },
    {
     "ref": "107:4",
     "ar": "فَوَيْلٌ لِّلْمُصَلِّينَ",
     "en": "So woe to those who pray",
     "words": [
      {
       "ar": "فَوَيْلٌ",
       "en": "So woe",
       "root": ""
      },
      {
       "ar": "لِّلْمُصَلِّينَ",
       "en": "to those who pray",
       "root": "صلو"
      }
     ]
    },
    {
     "ref": "107:5",
     "ar": "الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ",
     "en": "who are heedless of their prayer,",
     "words": [
      {
       "ar": "الَّذِينَ",
       "en": "who",
       "root": ""
      },
      {
       "ar": "هُمْ",
       "en": "they",
       "root": ""
      },
      {
       "ar": "عَن",
       "en": "of",
       "root": ""
      },
      {
       "ar": "صَلَاتِهِمْ",
       "en": "their prayer",
       "root": "صلو"
      },
      {
       "ar": "سَاهُونَ",
       "en": "are heedless",
       "root": "سهو"
      }
     ]
    },
    {
     "ref": "107:6",
     "ar": "الَّذِينَ هُمْ يُرَاءُونَ",
     "en": "those who show off,",
     "words": [
      {
       "ar": "الَّذِينَ",
       "en": "those who",
       "root": ""
      },
      {
       "ar": "هُمْ",
       "en": "they",
       "root": ""
      },
      {
       "ar": "يُرَاءُونَ",
       "en": "show off",
       "root": "رأي"
      }
     ]
    },
    {
     "ref": "107:7",
     "ar": "وَيَمْنَعُونَ الْمَاعُونَ",
     "en": "and hold back small kindnesses.",
     "words": [
      {
       "ar": "وَيَمْنَعُونَ",
       "en": "and hold back",
       "root": "منع"
      },
      {
       "ar": "الْمَاعُونَ",
       "en": "small kindnesses",
       "root": "عون"
      }
     ]
    }
   ]
  },
  {
   "id": "quraysh",
   "title": "Quraysh",
   "ar_title": "قُرَيْشٌ",
   "what": "Quraysh: gratitude for safety and food.",
   "group": "surah",
   "surah": 106,
   "lines": [
    {
     "ref": "106:1",
     "ar": "لِإِيلَافِ قُرَيْشٍ",
     "en": "For the security of Quraysh,",
     "words": [
      {
       "ar": "لِإِيلَافِ",
       "en": "For the security",
       "root": "ألف"
      },
      {
       "ar": "قُرَيْشٍ",
       "en": "of Quraysh",
       "root": "قرش"
      }
     ]
    },
    {
     "ref": "106:2",
     "ar": "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ",
     "en": "their security in the journeys of winter and summer,",
     "words": [
      {
       "ar": "إِيلَافِهِمْ",
       "en": "their security",
       "root": "ألف"
      },
      {
       "ar": "رِحْلَةَ",
       "en": "(in) the journey",
       "root": "رحل"
      },
      {
       "ar": "الشِّتَاءِ",
       "en": "of winter",
       "root": "شتو"
      },
      {
       "ar": "وَالصَّيْفِ",
       "en": "and summer",
       "root": "صيف"
      }
     ]
    },
    {
     "ref": "106:3",
     "ar": "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ",
     "en": "let them worship the Lord of this House,",
     "words": [
      {
       "ar": "فَلْيَعْبُدُوا",
       "en": "so let them worship",
       "root": "عبد"
      },
      {
       "ar": "رَبَّ",
       "en": "the Lord",
       "root": "ربب"
      },
      {
       "ar": "هَٰذَا",
       "en": "of this",
       "root": ""
      },
      {
       "ar": "الْبَيْتِ",
       "en": "House",
       "root": "بيت"
      }
     ]
    },
    {
     "ref": "106:4",
     "ar": "الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ",
     "en": "who fed them against hunger and made them safe from fear.",
     "words": [
      {
       "ar": "الَّذِي",
       "en": "who",
       "root": ""
      },
      {
       "ar": "أَطْعَمَهُم",
       "en": "fed them",
       "root": "طعم"
      },
      {
       "ar": "مِّن",
       "en": "against",
       "root": ""
      },
      {
       "ar": "جُوعٍ",
       "en": "hunger",
       "root": "جوع"
      },
      {
       "ar": "وَآمَنَهُم",
       "en": "and made them safe",
       "root": "أمن"
      },
      {
       "ar": "مِّنْ",
       "en": "from",
       "root": ""
      },
      {
       "ar": "خَوْفٍ",
       "en": "fear",
       "root": "خوف"
      }
     ]
    }
   ]
  },
  {
   "id": "fil",
   "title": "Al-Fil",
   "ar_title": "الفِيلُ",
   "what": "The elephant: the army that marched on the Ka'bah.",
   "group": "surah",
   "surah": 105,
   "lines": [
    {
     "ref": "105:1",
     "ar": "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ",
     "en": "Have you not seen how your Lord dealt with the people of the elephant?",
     "words": [
      {
       "ar": "أَلَمْ",
       "en": "Have not",
       "root": ""
      },
      {
       "ar": "تَرَ",
       "en": "you seen",
       "root": "رأي"
      },
      {
       "ar": "كَيْفَ",
       "en": "how",
       "root": "كيف"
      },
      {
       "ar": "فَعَلَ",
       "en": "dealt",
       "root": "فعل"
      },
      {
       "ar": "رَبُّكَ",
       "en": "your Lord",
       "root": "ربب"
      },
      {
       "ar": "بِأَصْحَابِ",
       "en": "with the people",
       "root": "صحب"
      },
      {
       "ar": "الْفِيلِ",
       "en": "of the elephant",
       "root": "فيل"
      }
     ]
    },
    {
     "ref": "105:2",
     "ar": "أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ",
     "en": "Did He not make their plan go astray?",
     "words": [
      {
       "ar": "أَلَمْ",
       "en": "Did not",
       "root": ""
      },
      {
       "ar": "يَجْعَلْ",
       "en": "He make",
       "root": "جعل"
      },
      {
       "ar": "كَيْدَهُمْ",
       "en": "their plan",
       "root": "كيد"
      },
      {
       "ar": "فِي",
       "en": "into",
       "root": ""
      },
      {
       "ar": "تَضْلِيلٍ",
       "en": "going astray",
       "root": "ضلل"
      }
     ]
    },
    {
     "ref": "105:3",
     "ar": "وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ",
     "en": "And He sent against them birds in flocks,",
     "words": [
      {
       "ar": "وَأَرْسَلَ",
       "en": "And He sent",
       "root": "رسل"
      },
      {
       "ar": "عَلَيْهِمْ",
       "en": "against them",
       "root": ""
      },
      {
       "ar": "طَيْرًا",
       "en": "birds",
       "root": "طير"
      },
      {
       "ar": "أَبَابِيلَ",
       "en": "in flocks",
       "root": "أبل"
      }
     ]
    },
    {
     "ref": "105:4",
     "ar": "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ",
     "en": "striking them with stones of baked clay,",
     "words": [
      {
       "ar": "تَرْمِيهِم",
       "en": "striking them",
       "root": "رمي"
      },
      {
       "ar": "بِحِجَارَةٍ",
       "en": "with stones",
       "root": "حجر"
      },
      {
       "ar": "مِّن",
       "en": "of",
       "root": ""
      },
      {
       "ar": "سِجِّيلٍ",
       "en": "baked clay",
       "root": "سجل"
      }
     ]
    },
    {
     "ref": "105:5",
     "ar": "فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ",
     "en": "and He made them like eaten-up straw.",
     "words": [
      {
       "ar": "فَجَعَلَهُمْ",
       "en": "and He made them",
       "root": "جعل"
      },
      {
       "ar": "كَعَصْفٍ",
       "en": "like straw",
       "root": "عصف"
      },
      {
       "ar": "مَّأْكُولٍ",
       "en": "eaten up",
       "root": "أكل"
      }
     ]
    }
   ]
  }
 ],
 "links": {
  "46": [
   "أبو"
  ],
  "212": [
   "أحد"
  ],
  "289": [
   "أحد"
  ],
  "492": [
   "أحد"
  ],
  "165": [
   "أكل"
  ],
  "6": [
   "أله",
   "حمد"
  ],
  "69": [
   "أله",
   "سلم",
   "صلو"
  ],
  "70": [
   "أله",
   "كبر"
  ],
  "71": [
   "أله"
  ],
  "233": [
   "أله"
  ],
  "234": [
   "أله"
  ],
  "351": [
   "أله",
   "برك"
  ],
  "559": [
   "أله",
   "برك",
   "رحم",
   "سلم"
  ],
  "562": [
   "أله"
  ],
  "580": [
   "أله",
   "برك",
   "رحم",
   "سلم"
  ],
  "90": [
   "بيت"
  ],
  "52": [
   "جدد"
  ],
  "53": [
   "جدد"
  ],
  "205": [
   "جدد"
  ],
  "167": [
   "جوع"
  ],
  "747": [
   "جوع"
  ],
  "626": [
   "حبل"
  ],
  "773": [
   "حمل"
  ],
  "104": [
   "حيي"
  ],
  "107": [
   "دخل"
  ],
  "108": [
   "دخل"
  ],
  "470": [
   "دخل"
  ],
  "405": [
   "رأي"
  ],
  "595": [
   "رأي"
  ],
  "307": [
   "رحل"
  ],
  "308": [
   "رحل"
  ],
  "309": [
   "رحل"
  ],
  "406": [
   "رحل"
  ],
  "440": [
   "رحل"
  ],
  "478": [
   "رحل"
  ],
  "68": [
   "رسل"
  ],
  "461": [
   "رسل"
  ],
  "511": [
   "رمي"
  ],
  "442": [
   "سبح"
  ],
  "106": [
   "سكن"
  ],
  "1": [
   "سلم"
  ],
  "2": [
   "سلم"
  ],
  "8": [
   "سلم"
  ],
  "428": [
   "سلم"
  ],
  "455": [
   "سلم"
  ],
  "560": [
   "سلم"
  ],
  "583": [
   "سلم"
  ],
  "227": [
   "سمع"
  ],
  "9": [
   "سمو"
  ],
  "10": [
   "سمو"
  ],
  "368": [
   "سمو"
  ],
  "371": [
   "شتو"
  ],
  "379": [
   "شتو"
  ],
  "115": [
   "شهد"
  ],
  "135": [
   "شهد"
  ],
  "564": [
   "صدر"
  ],
  "63": [
   "صلو"
  ],
  "64": [
   "صلو"
  ],
  "151": [
   "صلو"
  ],
  "218": [
   "صلو"
  ],
  "605": [
   "صلو"
  ],
  "374": [
   "صيف"
  ],
  "607": [
   "صيف"
  ],
  "179": [
   "طعم"
  ],
  "196": [
   "طعم"
  ],
  "235": [
   "طيب"
  ],
  "467": [
   "طيب",
   "قوم"
  ],
  "223": [
   "طير"
  ],
  "300": [
   "طير"
  ],
  "301": [
   "طير"
  ],
  "305": [
   "طير"
  ],
  "477": [
   "طير"
  ],
  "671": [
   "طير"
  ],
  "585": [
   "عطو"
  ],
  "658": [
   "عظم"
  ],
  "694": [
   "عقد"
  ],
  "696": [
   "عقد"
  ],
  "59": [
   "علم"
  ],
  "269": [
   "علم"
  ],
  "278": [
   "علم"
  ],
  "450": [
   "علم"
  ],
  "456": [
   "علم"
  ],
  "485": [
   "فتح"
  ],
  "634": [
   "فتح"
  ],
  "136": [
   "فعل"
  ],
  "633": [
   "فيل"
  ],
  "614": [
   "قول"
  ],
  "537": [
   "قوم"
  ],
  "161": [
   "كبر"
  ],
  "191": [
   "كثر"
  ],
  "270": [
   "كون"
  ],
  "618": [
   "كون"
  ],
  "3": [
   "كيف"
  ],
  "4": [
   "كيف"
  ],
  "383": [
   "كيف"
  ],
  "341": [
   "مرأ"
  ],
  "637": [
   "مول"
  ],
  "222": [
   "نبأ"
  ],
  "220": [
   "نور"
  ],
  "540": [
   "هدي"
  ],
  "713": [
   "هدي"
  ],
  "51": [
   "ولد"
  ],
  "56": [
   "ولد"
  ],
  "57": [
   "ولد"
  ],
  "639": [
   "ولد"
  ],
  "752": [
   "يدي"
  ],
  "152": [
   "يوم"
  ],
  "153": [
   "يوم"
  ],
  "283": [
   "يوم"
  ],
  "622": [
   "يوم"
  ],
  "760": [
   "يوم"
  ],
  "34": [
   "أحد"
  ],
  "466": [
   "قوم"
  ]
 },
 "where": {
  "أله": [
   [
    "takbir",
    0,
    0
   ],
   [
    "opening",
    0,
    1
   ],
   [
    "opening",
    0,
    8
   ],
   [
    "refuge",
    0,
    1
   ],
   [
    "fatiha1",
    0,
    1
   ],
   [
    "fatiha1",
    1,
    1
   ],
   [
    "rising",
    0,
    1
   ],
   [
    "tashahhud",
    0,
    1
   ],
   [
    "tashahhud",
    1,
    5
   ],
   [
    "tashahhud",
    2,
    4
   ],
   [
    "tashahhud",
    3,
    3
   ],
   [
    "tashahhud",
    3,
    5
   ],
   [
    "salawat",
    0,
    0
   ],
   [
    "salawat",
    2,
    0
   ],
   [
    "taslim",
    0,
    3
   ],
   [
    "ikhlas",
    0,
    2
   ],
   [
    "ikhlas",
    1,
    0
   ],
   [
    "nas",
    2,
    0
   ],
   [
    "nasr",
    0,
    3
   ],
   [
    "nasr",
    1,
    5
   ]
  ],
  "كبر": [
   [
    "takbir",
    0,
    1
   ]
  ],
  "سبح": [
   [
    "opening",
    0,
    0
   ],
   [
    "ruku",
    0,
    0
   ],
   [
    "sujud",
    0,
    0
   ],
   [
    "nasr",
    2,
    0
   ]
  ],
  "حمد": [
   [
    "opening",
    0,
    2
   ],
   [
    "fatiha1",
    1,
    0
   ],
   [
    "rising",
    0,
    3
   ],
   [
    "rising",
    1,
    2
   ],
   [
    "tashahhud",
    3,
    8
   ],
   [
    "salawat",
    0,
    3
   ],
   [
    "salawat",
    0,
    6
   ],
   [
    "salawat",
    1,
    8
   ],
   [
    "salawat",
    2,
    3
   ],
   [
    "salawat",
    2,
    6
   ],
   [
    "salawat",
    3,
    8
   ],
   [
    "nasr",
    2,
    1
   ]
  ],
  "برك": [
   [
    "opening",
    0,
    3
   ],
   [
    "tashahhud",
    1,
    6
   ],
   [
    "salawat",
    2,
    1
   ],
   [
    "salawat",
    3,
    1
   ]
  ],
  "سمو": [
   [
    "opening",
    0,
    4
   ],
   [
    "fatiha1",
    0,
    0
   ]
  ],
  "علو": [
   [
    "opening",
    0,
    5
   ],
   [
    "sujud",
    0,
    2
   ]
  ],
  "جدد": [
   [
    "opening",
    0,
    6
   ]
  ],
  "غير": [
   [
    "opening",
    0,
    9
   ],
   [
    "fatiha2",
    2,
    4
   ]
  ],
  "عوذ": [
   [
    "refuge",
    0,
    0
   ],
   [
    "falaq",
    0,
    1
   ],
   [
    "nas",
    0,
    1
   ]
  ],
  "شطن": [
   [
    "refuge",
    0,
    3
   ]
  ],
  "رجم": [
   [
    "refuge",
    0,
    4
   ]
  ],
  "رحم": [
   [
    "fatiha1",
    0,
    2
   ],
   [
    "fatiha1",
    0,
    3
   ],
   [
    "fatiha1",
    2,
    0
   ],
   [
    "fatiha1",
    2,
    1
   ],
   [
    "tashahhud",
    1,
    4
   ],
   [
    "taslim",
    0,
    2
   ]
  ],
  "ربب": [
   [
    "fatiha1",
    1,
    2
   ],
   [
    "ruku",
    0,
    1
   ],
   [
    "rising",
    1,
    0
   ],
   [
    "sujud",
    0,
    1
   ],
   [
    "sujud",
    1,
    0
   ],
   [
    "falaq",
    0,
    2
   ],
   [
    "nas",
    0,
    2
   ],
   [
    "kawthar",
    1,
    1
   ],
   [
    "nasr",
    2,
    2
   ],
   [
    "quraysh",
    2,
    1
   ],
   [
    "fil",
    0,
    4
   ]
  ],
  "علم": [
   [
    "fatiha1",
    1,
    3
   ]
  ],
  "ملك": [
   [
    "fatiha1",
    3,
    0
   ],
   [
    "nas",
    1,
    0
   ]
  ],
  "يوم": [
   [
    "fatiha1",
    3,
    1
   ]
  ],
  "دين": [
   [
    "fatiha1",
    3,
    2
   ],
   [
    "nasr",
    1,
    4
   ],
   [
    "kafirun",
    5,
    1
   ],
   [
    "kafirun",
    5,
    3
   ],
   [
    "maun",
    0,
    3
   ]
  ],
  "عبد": [
   [
    "fatiha2",
    0,
    1
   ],
   [
    "tashahhud",
    2,
    3
   ],
   [
    "tashahhud",
    3,
    9
   ],
   [
    "kafirun",
    1,
    1
   ],
   [
    "kafirun",
    1,
    3
   ],
   [
    "kafirun",
    2,
    2
   ],
   [
    "kafirun",
    2,
    4
   ],
   [
    "kafirun",
    3,
    2
   ],
   [
    "kafirun",
    3,
    4
   ],
   [
    "kafirun",
    4,
    2
   ],
   [
    "kafirun",
    4,
    4
   ],
   [
    "quraysh",
    2,
    0
   ]
  ],
  "عون": [
   [
    "fatiha2",
    0,
    3
   ],
   [
    "maun",
    6,
    1
   ]
  ],
  "هدي": [
   [
    "fatiha2",
    1,
    0
   ]
  ],
  "صرط": [
   [
    "fatiha2",
    1,
    1
   ],
   [
    "fatiha2",
    2,
    0
   ]
  ],
  "قوم": [
   [
    "fatiha2",
    1,
    2
   ]
  ],
  "نعم": [
   [
    "fatiha2",
    2,
    2
   ]
  ],
  "غضب": [
   [
    "fatiha2",
    2,
    5
   ]
  ],
  "ضلل": [
   [
    "fatiha2",
    2,
    8
   ],
   [
    "fil",
    1,
    4
   ]
  ],
  "عظم": [
   [
    "ruku",
    0,
    2
   ]
  ],
  "سمع": [
   [
    "rising",
    0,
    0
   ]
  ],
  "غفر": [
   [
    "sujud",
    1,
    1
   ],
   [
    "nasr",
    2,
    3
   ]
  ],
  "حيي": [
   [
    "tashahhud",
    0,
    0
   ]
  ],
  "صلو": [
   [
    "tashahhud",
    0,
    2
   ],
   [
    "salawat",
    0,
    1
   ],
   [
    "salawat",
    1,
    1
   ],
   [
    "kawthar",
    1,
    0
   ],
   [
    "maun",
    3,
    1
   ],
   [
    "maun",
    4,
    3
   ]
  ],
  "طيب": [
   [
    "tashahhud",
    0,
    3
   ]
  ],
  "سلم": [
   [
    "tashahhud",
    1,
    0
   ],
   [
    "tashahhud",
    2,
    0
   ],
   [
    "taslim",
    0,
    0
   ]
  ],
  "نبأ": [
   [
    "tashahhud",
    1,
    3
   ]
  ],
  "صلح": [
   [
    "tashahhud",
    2,
    5
   ]
  ],
  "شهد": [
   [
    "tashahhud",
    3,
    0
   ],
   [
    "tashahhud",
    3,
    6
   ]
  ],
  "رسل": [
   [
    "tashahhud",
    3,
    10
   ],
   [
    "fil",
    2,
    0
   ]
  ],
  "أول": [
   [
    "salawat",
    0,
    5
   ],
   [
    "salawat",
    1,
    5
   ],
   [
    "salawat",
    2,
    5
   ],
   [
    "salawat",
    3,
    5
   ]
  ],
  "مجد": [
   [
    "salawat",
    1,
    9
   ],
   [
    "salawat",
    3,
    9
   ]
  ],
  "قول": [
   [
    "ikhlas",
    0,
    0
   ],
   [
    "falaq",
    0,
    0
   ],
   [
    "nas",
    0,
    0
   ],
   [
    "kafirun",
    0,
    0
   ]
  ],
  "أحد": [
   [
    "ikhlas",
    0,
    3
   ],
   [
    "ikhlas",
    3,
    4
   ]
  ],
  "صمد": [
   [
    "ikhlas",
    1,
    1
   ]
  ],
  "ولد": [
   [
    "ikhlas",
    2,
    1
   ],
   [
    "ikhlas",
    2,
    3
   ]
  ],
  "كون": [
   [
    "ikhlas",
    3,
    1
   ],
   [
    "nasr",
    2,
    5
   ]
  ],
  "كفأ": [
   [
    "ikhlas",
    3,
    3
   ]
  ],
  "فلق": [
   [
    "falaq",
    0,
    3
   ]
  ],
  "شرر": [
   [
    "falaq",
    1,
    1
   ],
   [
    "falaq",
    2,
    1
   ],
   [
    "falaq",
    3,
    1
   ],
   [
    "falaq",
    4,
    1
   ],
   [
    "nas",
    3,
    1
   ]
  ],
  "خلق": [
   [
    "falaq",
    1,
    3
   ]
  ],
  "غسق": [
   [
    "falaq",
    2,
    2
   ]
  ],
  "وقب": [
   [
    "falaq",
    2,
    4
   ]
  ],
  "نفث": [
   [
    "falaq",
    3,
    2
   ]
  ],
  "عقد": [
   [
    "falaq",
    3,
    4
   ]
  ],
  "حسد": [
   [
    "falaq",
    4,
    2
   ],
   [
    "falaq",
    4,
    4
   ]
  ],
  "أنس": [
   [
    "nas",
    0,
    3
   ],
   [
    "nas",
    1,
    1
   ],
   [
    "nas",
    2,
    1
   ],
   [
    "nas",
    4,
    4
   ],
   [
    "nas",
    5,
    2
   ],
   [
    "nasr",
    1,
    1
   ]
  ],
  "وسوس": [
   [
    "nas",
    3,
    2
   ],
   [
    "nas",
    4,
    1
   ]
  ],
  "خنس": [
   [
    "nas",
    3,
    3
   ]
  ],
  "صدر": [
   [
    "nas",
    4,
    3
   ]
  ],
  "جنن": [
   [
    "nas",
    5,
    1
   ]
  ],
  "عطو": [
   [
    "kawthar",
    0,
    1
   ]
  ],
  "كثر": [
   [
    "kawthar",
    0,
    2
   ]
  ],
  "نحر": [
   [
    "kawthar",
    1,
    2
   ]
  ],
  "شنأ": [
   [
    "kawthar",
    2,
    1
   ]
  ],
  "بتر": [
   [
    "kawthar",
    2,
    3
   ]
  ],
  "جيأ": [
   [
    "nasr",
    0,
    1
   ]
  ],
  "نصر": [
   [
    "nasr",
    0,
    2
   ]
  ],
  "فتح": [
   [
    "nasr",
    0,
    4
   ]
  ],
  "رأي": [
   [
    "nasr",
    1,
    0
   ],
   [
    "maun",
    0,
    0
   ],
   [
    "maun",
    5,
    2
   ],
   [
    "fil",
    0,
    1
   ]
  ],
  "دخل": [
   [
    "nasr",
    1,
    2
   ]
  ],
  "فوج": [
   [
    "nasr",
    1,
    6
   ]
  ],
  "توب": [
   [
    "nasr",
    2,
    6
   ]
  ],
  "كفر": [
   [
    "kafirun",
    0,
    3
   ]
  ],
  "تبب": [
   [
    "masad",
    0,
    0
   ],
   [
    "masad",
    0,
    4
   ]
  ],
  "يدي": [
   [
    "masad",
    0,
    1
   ]
  ],
  "أبو": [
   [
    "masad",
    0,
    2
   ]
  ],
  "لهب": [
   [
    "masad",
    0,
    3
   ],
   [
    "masad",
    2,
    3
   ]
  ],
  "غني": [
   [
    "masad",
    1,
    1
   ]
  ],
  "مول": [
   [
    "masad",
    1,
    3
   ]
  ],
  "كسب": [
   [
    "masad",
    1,
    5
   ]
  ],
  "صلي": [
   [
    "masad",
    2,
    0
   ]
  ],
  "نور": [
   [
    "masad",
    2,
    1
   ]
  ],
  "مرأ": [
   [
    "masad",
    3,
    0
   ]
  ],
  "حمل": [
   [
    "masad",
    3,
    1
   ]
  ],
  "حطب": [
   [
    "masad",
    3,
    2
   ]
  ],
  "جيد": [
   [
    "masad",
    4,
    1
   ]
  ],
  "حبل": [
   [
    "masad",
    4,
    2
   ]
  ],
  "مسد": [
   [
    "masad",
    4,
    4
   ]
  ],
  "كذب": [
   [
    "maun",
    0,
    2
   ]
  ],
  "دعع": [
   [
    "maun",
    1,
    2
   ]
  ],
  "يتم": [
   [
    "maun",
    1,
    3
   ]
  ],
  "حضض": [
   [
    "maun",
    2,
    1
   ]
  ],
  "طعم": [
   [
    "maun",
    2,
    3
   ],
   [
    "quraysh",
    3,
    1
   ]
  ],
  "سكن": [
   [
    "maun",
    2,
    4
   ]
  ],
  "سهو": [
   [
    "maun",
    4,
    4
   ]
  ],
  "منع": [
   [
    "maun",
    6,
    0
   ]
  ],
  "ألف": [
   [
    "quraysh",
    0,
    0
   ],
   [
    "quraysh",
    1,
    0
   ]
  ],
  "قرش": [
   [
    "quraysh",
    0,
    1
   ]
  ],
  "رحل": [
   [
    "quraysh",
    1,
    1
   ]
  ],
  "شتو": [
   [
    "quraysh",
    1,
    2
   ]
  ],
  "صيف": [
   [
    "quraysh",
    1,
    3
   ]
  ],
  "بيت": [
   [
    "quraysh",
    2,
    3
   ]
  ],
  "جوع": [
   [
    "quraysh",
    3,
    3
   ]
  ],
  "أمن": [
   [
    "quraysh",
    3,
    4
   ]
  ],
  "خوف": [
   [
    "quraysh",
    3,
    6
   ]
  ],
  "كيف": [
   [
    "fil",
    0,
    2
   ]
  ],
  "فعل": [
   [
    "fil",
    0,
    3
   ]
  ],
  "صحب": [
   [
    "fil",
    0,
    5
   ]
  ],
  "فيل": [
   [
    "fil",
    0,
    6
   ]
  ],
  "جعل": [
   [
    "fil",
    1,
    1
   ],
   [
    "fil",
    4,
    0
   ]
  ],
  "كيد": [
   [
    "fil",
    1,
    2
   ]
  ],
  "طير": [
   [
    "fil",
    2,
    2
   ]
  ],
  "أبل": [
   [
    "fil",
    2,
    3
   ]
  ],
  "رمي": [
   [
    "fil",
    3,
    0
   ]
  ],
  "حجر": [
   [
    "fil",
    3,
    1
   ]
  ],
  "سجل": [
   [
    "fil",
    3,
    3
   ]
  ],
  "عصف": [
   [
    "fil",
    4,
    1
   ]
  ],
  "أكل": [
   [
    "fil",
    4,
    2
   ]
  ]
 }
};
