/* salah-timings.js: GENERATED by tools/align-salah.js (ElevenLabs forced alignment).
   When each word is said in the recorded prayer phrases, per clip: [[startMs, endMs], …]. */
const SALAH_TIMINGS = {};
