"""Builds salah-data.js (the "Your salah" track) from tools/salah/content.py
and tools/salah/quran-subset.json, and checks that every Quran word has a
meaning. Run: python3 tools/salah/build.py

quran-subset.json holds Al-Fatiha and surahs 105-114: the text is the Tanzil
Quran Text (Simple), used verbatim under CC BY 3.0 with its notice kept; the
roots come from the Quranic Arabic Corpus morphology. Nothing here is live in
the app until a teacher has approved it (status below)."""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from content import PARTS, SURAHS, QURAN

ROOT = os.path.dirname(os.path.dirname(HERE))
q = json.load(open(os.path.join(HERE, 'quran-subset.json'), encoding='utf8'))
ayat = q['ayat']
errors = []

def w(ar, en, root):
    return {'ar': ar, 'en': en, 'root': root}

def quran_line(ref):
    words = ayat[ref]
    if ref not in QURAN:
        errors.append(f'{ref}: no meaning written'); return None
    en, glosses = QURAN[ref]
    if len(glosses) != len(words):
        errors.append(f'{ref}: {len(words)} words but {len(glosses)} meanings')
        glosses = (glosses + [''] * len(words))[:len(words)]
    return {'ref': ref, 'ar': ' '.join(a for a, _ in words), 'en': en,
            'words': [w(a, g, r) for (a, r), g in zip(words, glosses)]}

def prayer_line(l):
    return {'ar': ' '.join(x[0] for x in l['words']), 'en': l['en'],
            'words': [w(*x) for x in l['words']], **({'review_note': l['review_note']} if 'review_note' in l else {})}

out = []
for p in PARTS:
    part = {k: p[k] for k in ('id', 'title', 'ar_title', 'what')}
    part['group'] = 'prayer'
    if 'review_note' in p: part['review_note'] = p['review_note']
    if 'quran' in p:
        part['lines'] = [quran_line(r) for r in p['quran']]
        if 'after' in p: part['lines'].append(prayer_line(p['after']))
    else:
        part['lines'] = [prayer_line(l) for l in p['lines']]
    out.append(part)
for s in SURAHS:
    refs = sorted((k for k in ayat if k.split(':')[0] == str(s['n'])), key=lambda k: int(k.split(':')[1]))
    out.append({'id': s['id'], 'title': s['title'], 'ar_title': s['ar_title'], 'what': s['what'],
                'group': 'surah', 'surah': s['n'], 'lines': [quran_line(r) for r in refs]})

# Course words that share a root with a salah word (tools/salah/links.json,
# accepted by hand after TypeSafe): vocab id -> roots, and root -> where it
# is said in salah as [part id, line index, word index].
links = json.load(open(os.path.join(HERE, 'links.json'), encoding='utf8'))['links']
by_word = {}
for l in links:
    if l['decision'] == 'accept':
        by_word.setdefault(str(l['id']), [])
        if l['root'] not in by_word[str(l['id'])]: by_word[str(l['id'])].append(l['root'])
where = {}
for p in out:
    for li, line in enumerate(p['lines']):
        for wi, x in enumerate(line['words']):
            if x['root']: where.setdefault(x['root'], []).append([p['id'], li, wi])
for wid, rs in by_word.items():
    for r in rs:
        if r not in where: errors.append(f'link {wid} -> {r}: root not said in salah')

if errors:
    print('\n'.join(errors)); sys.exit(1)

data = {'status': 'awaiting teacher review',
        'sources': ['Quran text: Tanzil Project (tanzil.net), Tanzil Quran Text (Simple), CC BY 3.0, used verbatim.',
                    'Roots of Quran words: Quranic Arabic Corpus (corpus.quran.com), morphology v0.4.',
                    'Quran meanings: shown in the app from the Quran Foundation (translation: Saheeh International; word by word: Quran.com), loaded live; the ones here are only the fallback when it can\'t be reached.',
                    'Prayer phrases (not Quran): Rafiq drafts, awaiting teacher review.'],
        'parts': out, 'links': by_word, 'where': where}
js = ('/* salah-data.js: the "Your salah" track. GENERATED by tools/salah/build.py; edit\n'
      '   tools/salah/content.py instead. Status: ' + data['status'] + '.\n'
      '   Quran text: Tanzil Project (tanzil.net), CC BY 3.0, verbatim. */\n'
      'const SALAH = ' + json.dumps(data, ensure_ascii=False, indent=1) + ';\n')
open(os.path.join(ROOT, 'salah-data.js'), 'w', encoding='utf8').write(js)
n = sum(len(l['words']) for p in out for l in p['lines'])
print(f'salah-data.js: {len(out)} parts, {sum(len(p["lines"]) for p in out)} lines, {n} words, '
      f'{len({x["root"] for p in out for l in p["lines"] for x in l["words"] if x["root"]})} roots')

# The teacher's review sheet: every line, every word, every link, with a box to tick.
R = ['# Your salah: review sheet', '',
     '**Status: awaiting teacher review.** Nothing here is shown to learners until it is approved.', '',
     'Please check each line: the Arabic wording, the English meaning of the line and of each word, and the root. '
     'Mark ✅ or write the correction next to it. Where a part has a note, please choose the wording you want taught.', '',
     'Sources: ' + ' '.join(data['sources']), '']
for p in out:
    R += [f"## {p['title']} · {p['ar_title']}", '', f"_{p['what']}_", '']
    if p.get('review_note'): R += [f"> **For the teacher:** {p['review_note']}", '']
    for line in p['lines']:
        ref = f" ({line['ref']})" if 'ref' in line else ''
        R += [f"- [ ] **{line['ar']}**{ref}", f"  {line['en']}", '']
        if line.get('review_note'): R += [f"  > **For the teacher:** {line['review_note']}", '']
        R += ['  | Arabic | Meaning | Root |', '  |---|---|---|']
        R += [f"  | {x['ar']} | {x['en']} | {'-'.join(x['root']) if x['root'] else '—'} |" for x in line['words']]
        R.append('')
R += ['## Links from everyday lessons to salah', '',
      'After a lesson, learners will see "🕌 You\'ll hear this in your salah" for these words. '
      'Please tick the ones that are right and helpful, and cross out any that would mislead.', '',
      '| ✓ | Course word | Meaning | Root | Said in salah as | Note |', '|---|---|---|---|---|---|']
first = {}
for p in out:
    for line in p['lines']:
        for x in line['words']:
            if x['root'] and x['root'] not in first: first[x['root']] = f"{x['ar']} ({x['en']}, {p['title']})"
for l in sorted((l for l in links if l['decision'] == 'accept'), key=lambda l: (l['root'], l['id'])):
    R.append(f"| [ ] | {l['ar']} | {l['en']} | {'-'.join(l['root'])} | {first[l['root']]} | {l.get('note', '')} |")
R += ['', f"<details><summary>{sum(l['decision'] == 'reject' for l in links)} suggested links rejected on review (for reference)</summary>", '',
      '| Course word | Root | Why rejected |', '|---|---|---|']
R += [f"| {l['ar']} | {'-'.join(l['root'])} | {l['why']} |" for l in links if l['decision'] == 'reject']
R += ['', '</details>', '']
open(os.path.join(HERE, 'REVIEW.md'), 'w', encoding='utf8').write('\n'.join(R))
print('tools/salah/REVIEW.md written')
