#!/usr/bin/env node
/* align-salah.js — when each word is said in the recorded prayer phrases of Your salah,
   so Follow along and Pray along light each word exactly as it's heard (#135).
   Sends each clip and its text to ElevenLabs forced alignment and writes
   salah-timings.js: { clipId: [[startMs, endMs], … one per word] }.
   Quran lines are not here: their timings come with the licensed recitation.
   Run by the "Align salah audio" Action (needs ELEVENLABS_API_KEY).            */
const fs = require('fs'), path = require('path'), root = path.join(__dirname, '..');
const KEY = process.env.ELEVENLABS_API_KEY;

// the same clip lookup as audio.js
const aid = s => { let h = 5381; for (let i = 0; i < s.length; i++) h = ((h * 33) ^ s.charCodeAt(i)) >>> 0; return h.toString(36); };
const bare = s => String(s).replace(/[؟?!.،,:؛]/g, ' ').replace(/\s+/g, ' ').trim();
const CLIPS = new Set(JSON.parse(fs.readFileSync(path.join(root, 'audio/index.json'), 'utf8')));
const clipId = t => CLIPS.has(aid(t)) ? aid(t) : CLIPS.has(aid(bare(t))) ? aid(bare(t)) : null;

let src = fs.readFileSync(path.join(root, 'salah-data.js'), 'utf8').replace(/const\s+SALAH\s*=/, 'globalThis.SALAH=');
eval(src);
const isQuran = p => p.group === 'surah' || /^fatiha/.test(p.id);

/* Each word of the line: [start, end] in ms. Uses the aligner's words when they match
   the line's words one for one, otherwise its characters, found by position. */
function perWord(line, res) {
  const toks = line.ar.split(/\s+/).filter(Boolean);
  const words = (res.words || []).filter(w => w.text && w.text.trim());
  if (words.length === toks.length) return words.map(w => [Math.round(w.start * 1000), Math.round(w.end * 1000)]);
  const chars = res.characters || [];
  if (chars.length !== line.ar.length) return null;
  const out = []; let at = 0;
  for (const t of toks) {
    const i = line.ar.indexOf(t, at); if (i < 0) return null;
    const cs = chars.slice(i, i + t.length); at = i + t.length;
    out.push([Math.round(cs[0].start * 1000), Math.round(cs[cs.length - 1].end * 1000)]);
  }
  return out;
}

(async () => {
  if (!KEY) { console.error('ELEVENLABS_API_KEY is not set'); process.exit(1); }
  const timings = {}, report = [];
  for (const p of SALAH.parts.filter(p => !isQuran(p))) for (const line of p.lines) {
    const id = clipId(line.ar);
    if (!id) { report.push(`${p.id}: no recording for "${line.ar}"`); continue; }
    if (timings[id]) continue;
    const form = new FormData();
    form.append('file', new Blob([fs.readFileSync(path.join(root, 'audio', id + '.mp3'))], { type: 'audio/mpeg' }), id + '.mp3');
    form.append('text', line.ar);
    const r = await fetch('https://api.elevenlabs.io/v1/forced-alignment', { method: 'POST', headers: { 'xi-api-key': KEY }, body: form });
    if (!r.ok) { report.push(`${p.id} ${id}: aligner ${r.status} ${(await r.text()).slice(0, 200)}`); continue; }
    const res = await r.json(), t = perWord(line, res);
    if (!t) { report.push(`${p.id} ${id}: couldn't match the aligner's words to the line`); continue; }
    timings[id] = t;
    report.push(`${p.id} ${id}: ${t.length} words, loss ${(res.loss ?? 0).toFixed(3)} ${JSON.stringify(t)}`);
  }
  fs.writeFileSync(path.join(root, 'salah-timings.js'),
    '/* salah-timings.js: GENERATED by tools/align-salah.js (ElevenLabs forced alignment).\n' +
    '   When each word is said in the recorded prayer phrases, per clip: [[startMs, endMs], …]. */\n' +
    'const SALAH_TIMINGS = ' + JSON.stringify(timings, null, 1) + ';\n');
  console.log(report.join('\n'));
  console.log(`\n${Object.keys(timings).length} clips aligned -> salah-timings.js`);
})();
